# Pandas Dataframes

In this notebook, you will learn about `Pandas` dataframes, a data structure in `Python` that provides the ability to work with **tabular data**. `Pandas` dataframes are composed of **rows** and **columns** that can have header names, and the columns in `pandas` dataframes can be different types (e.g. the first column containing integers and the second column containing text strings). Each value in a `pandas` dataframe is referred to as a cell that has a specific row index and column index within the tabular structure.

Read more about working with `pandas` dataframes in our open [Earth Data Science textbook](https://www.earthdatascience.org/courses/intro-to-earth-data-science/scientific-data-structures-python/pandas-dataframes/).

The [documentation](https://pandas.pydata.org/docs/user_guide/index.html) for the `pandas` library may also be useful.

In [1]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Open Colombia airports .csv 
# Data are from: https://ourairports.com/countries/CO/

# Define url
col_airports_url = "https://ourairports.com/countries/CO/airports.csv"

# Open data with pandas and return first 5 rows
airportDF = pd.read_csv(col_airports_url)
airportDF.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,country_name,iso_country,...,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords,score,last_updated
0,6104,SKBO,large_airport,El Dorado International Airport,4.70159,-74.1469,8361.0,NaN,Colombia,CO,...,Bogota,1,SKBO,BOG,BOG,https://eldorado.aero/,https://en.wikipedia.org/wiki/El_Dorado_Intern...,Cundinamarca,51275,2023-12-15T12:55:30+00:00
1,6109,SKCG,medium_airport,Rafael Nuñez International Airport,10.44240,-75.5130,4.0,SA,Colombia,CO,...,Cartagena,1,SKCG,CTG,CTG,NaN,https://en.wikipedia.org/wiki/Rafael_N%C3%BA%C...,NaN,750,2009-10-20T10:46:09+00:00
2,6158,SKRG,medium_airport,Jose Maria Córdova International Airport,6.16454,-75.4231,6955.0,SA,Colombia,CO,...,Medellín,1,SKRG,MDE,MDE,NaN,https://en.wikipedia.org/wiki/Jos%C3%A9_Mar%C3...,NaN,750,2017-08-14T21:49:57+00:00
3,6110,SKCL,medium_airport,Alfonso Bonilla Aragon International Airport,3.54322,-76.3816,3162.0,SA,Colombia,CO,...,Cali,1,SKCL,CLO,CLO,https://www.aerocali.com.co/,https://en.wikipedia.org/wiki/Alfonso_Bonilla_...,"Palmaseca International, 02-20",750,2019-08-15T00:05:28+00:00
4,6105,SKBQ,medium_airport,Ernesto Cortissoz International Airport,10.88960,-74.7808,98.0,SA,Colombia,CO,...,Barranquilla,1,SKBQ,BAQ,BAQ,NaN,https://en.wikipedia.org/wiki/Ernesto_Cortisso...,NaN,750,2009-10-20T10:46:07+00:00

In [4]:
# Return names of column headers using .column attribute
airportDF.columns

Index(['id', 'ident', 'type', 'name', 'latitude_deg', 'longitude_deg',
       'elevation_ft', 'continent', 'country_name', 'iso_country',
       'region_name', 'iso_region', 'local_region', 'municipality',
       'scheduled_service', 'gps_code', 'iata_code', 'local_code', 'home_link',
       'wikipedia_link', 'keywords', 'score', 'last_updated'],
      dtype='object')

In [5]:
# Explore the data using .info() method
airportDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 731 non-null    int64
 1   ident              731 non-null    object
 2   type               731 non-null    object
 3   name               731 non-null    object
 4   latitude_deg       731 non-null    float64
 5   longitude_deg      731 non-null    float64
 6   elevation_ft       672 non-null    float64
 7   continent          676 non-null    object
 8   country_name       731 non-null    object
 9   iso_country        731 non-null    object
 10  region_name        731 non-null    object
 11  iso_region         731 non-null    object
 12  local_region       731 non-null    object
 13  municipality       727 non-null    object
 14  scheduled_service  731 non-null    int64
 15  gps_code           147 non-null    object
 16  iata_code          144 non-null    object
 17  local_code         654 non-null    object
 18  home_link          8 non-null      object
 19  wikipedia_link     101 non-null    object
 20  keywords           29 non-null     object
 21  score              731 non-null    int64
 22  last_updated       731 non-null    object
dtypes: float64(3), int64(3), object(17)
memory usage: 131.5+ KB

In [6]:
# Return summary statistics using the .describe() method
airportDF.describe()

,id,latitude_deg,longitude_deg,elevation_ft,scheduled_service,score
count,731.000000,731.000000,731.000000,672.000000,731.000000,731.000000
mean,55394.348837,5.281830,-73.744583,1211.748512,0.071135,161.730506
std,80945.517680,2.858792,2.161402,1731.342925,0.257227,1900.207734
min,1644.000000,-4.193550,-81.711200,3.000000,0.000000,0.000000
25%,40619.500000,3.752639,-75.257663,319.000000,0.000000,50.000000
50%,40803.000000,4.746389,-73.672500,608.000000,0.000000,50.000000
75%,40986.500000,7.108970,-72.361527,1041.750000,0.000000,50.000000
max,519298.000000,13.357461,-67.081400,13119.000000,1.000000,51275.000000

In [7]:
# Transpose (flip row/column) the data using the .T attribute or .transpose() method
airportDF.T

,0,1,2,3,4,5,6,7,8,9,...,721,722,723,724,725,726,727,728,729,730
id,6104,6109,6158,6110,6105,6163,6161,6148,6132,6108,...,45116,45110,45112,45114,355179,45104,45105,45115,45101,353413
ident,SKBO,SKCG,SKRG,SKCL,SKBQ,SKSP,SKSM,SKPE,SKMD,SKCC,...,CO-0015,CO-0009,CO-0011,CO-0013,CO-0076,CO-0003,CO-0004,CO-0014,SKSF,CO-0072
type,large_airport,medium_airport,medium_airport,medium_airport,medium_airport,medium_airport,medium_airport,medium_airport,medium_airport,medium_airport,...,heliport,heliport,heliport,heliport,closed,heliport,heliport,heliport,closed,heliport
name,El Dorado International Airport,Rafael Nuñez International Airport,Jose Maria Córdova International Airport,Alfonso Bonilla Aragon International Airport,Ernesto Cortissoz International Airport,Gustavo Rojas Pinilla International Airport,Simón Bolívar International Airport,Matecaña International Airport,Enrique Olaya Herrera Airport,Camilo Daza International Airport,...,Cofa Montenegro Heliport,Isa Palmira Heliport,Helivalle Heliport,Cofa-Palmira Heliport,Papunahua River 2 Airstrip,Banco De La Republica Heliport,Banco De La Republica Heliport,Cofa Roldanillo Heliport,Santa Fé de Antioquía Airport,Carlos Haime University Hospital Helipad
latitude_deg,4.70159,10.4424,6.16454,3.54322,10.8896,12.5836,11.1196,4.81267,6.220549,7.92757,...,4.508333,3.537778,3.558889,3.514722,1.689703,1.196944,5.6975,4.413611,6.500631,10.5084
longitude_deg,-74.1469,-75.513,-75.4231,-76.3816,-74.7808,-81.7112,-74.2306,-75.7395,-75.590582,-72.5115,...,-75.786389,-76.401111,-76.306389,-76.305556,-71.114314,-77.28,-76.665,-76.143333,-75.822521,-75.46766
elevation_ft,8361.0,4.0,6955.0,3162.0,98.0,19.0,22.0,4416.0,4949.0,1096.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500.0,20.0
continent,NaN,SA,SA,SA,SA,NaN,SA,SA,SA,SA,...,SA,SA,SA,SA,NaN,SA,SA,SA,SA,SA
country_name,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia,...,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia,Colombia
iso_country,CO,CO,CO,CO,CO,CO,CO,CO,CO,CO,...,CO,CO,CO,CO,CO,CO,CO,CO,CO,CO
region_name,Bogotá Capital District,Bolívar Department,Antioquía Department,Valle del Cauca Department,Atlántico Department,"San Andrés, Providencia y Santa Catalina Depar...",Magdalena Department,Risaralda Department,Antioquía Department,Norte de Santander Department,...,Quindio Department,Valle del Cauca Department,Valle del Cauca Department,Valle del Cauca Department,Vaupés Department,Nariño Department,Chocó Department,Valle del Cauca Department,Antioquía Department,Bolívar Department
iso_region,CO-DC,CO-BOL,CO-ANT,CO-VAC,CO-ATL,CO-SAP,CO-MAG,CO-RIS,CO-ANT,CO-NSA,...,CO-QUI,CO-VAC,CO-VAC,CO-VAC,CO-VAU,CO-NAR,CO-CHO,CO-VAC,CO-ANT,CO-BOL
local_region,DC,BOL,ANT,VAC,ATL,SAP,MAG,RIS,ANT,NSA,...,QUI,VAC,VAC,VAC,VAU,NAR,CHO,VAC,ANT,BOL
municipality,Bogota,Cartagena,Medellín,Cali,Barranquilla,San Andrés,Santa Marta,Pereira,Medellín,Cúcuta,...,Montenegro,Palmira,Palmira,Palmira,Papunahua,Pasto,Quibdo,Roldanillo,Santa Fé de Antioquía,Serena del Mar
scheduled_service,1,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
gps_code,SKBO,SKCG,SKRG,SKCL,SKBQ,SKSP,SKSM,SKPE,SKMD,SKCC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
iata_code,BOG,CTG,MDE,CLO,BAQ,ADZ,SMR,PEI,EOH,CUC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
local_code,BOG,CTG,MDE,CLO,BAQ,ADZ,SMR,PEI,EOH,CUC,...,1CO,NaN,HEA,COA,NaN,BNC,BND,ICR,NaN,NaN
home_link,https://eldorado.aero/,NaN,NaN,https://www.aerocali.com.co/,NaN,NaN,NaN,http://aeromate.gov.co,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wikipedia_link,https://en.wikipedia.org/wiki/El_Dorado_Intern...,https://en.wikipedia.org/wiki/Rafael_N%C3%BA%C...,https://en.wikipedia.org/wiki/Jos%C3%A9_Mar%C3...,https://en.wikipedia.org/wiki/Alfonso_Bonilla_...,https://en.wikipedia.org/wiki/Ernesto_Cortisso...,https://en.wikipedia.org/wiki/Gustavo_Rojas_Pi...,https://en.wikipedia.org/wiki/Sim%C3%B3n_Bol%C...,https://en.wikipedia.org/wiki/Mateca%C3%B1a_In...,https://en.wikipedia.org/wiki/Enrique_Olaya_He...,https://en.wikipedia.org/wiki/Camilo_Daza_Inte...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
keywords,Cundinamarca,NaN,NaN,"Palmaseca International, 02-20",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,SXOP,NaN,NaN,NaN,"SKSF, SKSF, SFA",NaN
score,51275,750,750,750,750,750,750,750,750,750,...,0,0,0,0,0,0,0,0,0,0
last_updated,2023-12-15T12:55:30+00:00,2009-10-20T10:46:09+00:00,2017-08-14T21:49:57+00:00,2019-08-15T00:05:28+00:00,2009-10-20T10:46:07+00:00,2023-07-28T19:24:02+00:00,2015-05-08T23:40:04+00:00,2019-09-26T06:33:21+00:00,2011-06-13T16:50:03+00:00,2009-10-20T10:46:08+00:00,...,2012-06-09T12:02:53+00:00,2010-08-30T07:47:36+00:00,2012-06-09T23:00:50+00:00,2012-06-09T12:18:03+00:00,2022-06-26T04:32:59+00:00,2012-06-09T11:20:37+00:00,2012-06-09T11:07:51+00:00,2012-06-09T12:06:00+00:00,2016-03-11T19:36:26+00:00,2022-03-08T20:56:28+00:00

In [8]:
# Select a single column and describe
airportDF.name.describe()

count                                731
unique                               662
top       Banco De La Republica Heliport
freq                                   9
Name: name, dtype: object

In [9]:
# Select first 5 rows (can also be done using .head())
airportDF['name'].head()

0                 El Dorado International Airport
1              Rafael Nuñez International Airport
2        Jose Maria Córdova International Airport
3    Alfonso Bonilla Aragon International Airport
4         Ernesto Cortissoz International Airport
Name: name, dtype: object

In [44]:
airportDF[10:21]

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,country_name,iso_country,...,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords,score,last_updated,elev > 5280,type_mid
10,6140,SKMZ,medium_airport,La Nubia Airport,5.029600,-75.464700,6871.0,SA,Colombia,CO,...,SKMZ,MZL,MZL,NaN,https://en.wikipedia.org/wiki/La_Nubia_Airport,NaN,750,2009-10-20T10:46:19+00:00,True,True
11,6155,SKPV,medium_airport,El Embrujo Airport,13.357461,-81.357977,10.0,NaN,Colombia,CO,...,SKPV,PVA,PVA,NaN,https://en.wikipedia.org/wiki/El_Embrujo_Airport,NaN,750,2023-07-28T19:20:52+00:00,False,True
12,6099,SKAR,medium_airport,El Eden Airport,4.452780,-75.766400,3990.0,SA,Colombia,CO,...,SKAR,AXM,AXM,NaN,https://en.wikipedia.org/wiki/El_Ed%C3%A9n_Air...,NaN,750,2019-09-26T06:31:17+00:00,False,True
13,6102,SKBG,medium_airport,Palonegro Airport,7.126500,-73.184800,3897.0,SA,Colombia,CO,...,SKBG,BGA,BGA,NaN,https://en.wikipedia.org/wiki/Palo_Negro_Inter...,NaN,750,2021-03-27T10:43:19+00:00,False,True
14,6159,SKRH,medium_airport,Almirante Padilla Airport,11.526200,-72.926000,43.0,SA,Colombia,CO,...,SKRH,RCH,RCH,NaN,https://en.wikipedia.org/wiki/Riohacha_Airport,NaN,750,2009-10-20T10:46:19+00:00,False,True
15,6177,SKVV,medium_airport,Vanguardia Airport,4.167870,-73.613800,1394.0,SA,Colombia,CO,...,SKVV,VVC,VVC,NaN,https://en.wikipedia.org/wiki/La_Vanguardia_Ai...,NaN,750,2009-10-20T10:46:27+00:00,False,True
16,6154,SKPS,medium_airport,Antonio Nariño Airport,1.396250,-77.291500,5951.0,NaN,Colombia,CO,...,SKPS,PSO,PSO,NaN,https://en.wikipedia.org/wiki/Antonio_Nari%C3%...,Pasto,750,2022-11-24T09:33:37+00:00,True,True
17,6130,SKLT,medium_airport,Alfredo Vásquez Cobo International Airport,-4.193550,-69.943200,277.0,SA,Colombia,CO,...,SKLT,LET,LET,NaN,https://en.wikipedia.org/wiki/V%C3%A1squez_Cob...,NaN,750,2009-10-20T10:46:17+00:00,False,True
18,6139,SKMU,medium_airport,Fabio Alberto Leon Bentley Airport,1.253660,-70.233900,680.0,SA,Colombia,CO,...,SKMU,MVP,MVP,NaN,https://en.wikipedia.org/wiki/Fabio_Alberto_Le...,NaN,750,2015-05-09T00:18:09+00:00,False,True
19,40906,SK-429,small_airport,Leticia Airport,4.463611,-75.033611,2197.0,SA,Colombia,CO,...,NaN,NaN,LCT,NaN,NaN,NaN,50,2009-10-20T10:45:58+00:00,False,False
20,6123,SKGY,small_airport,Guaymaral Airport,4.812330,-74.064900,8390.0,NaN,Colombia,CO,...,SKGY,NaN,GMY,NaN,https://en.wikipedia.org/wiki/Guaymaral_Airport,NaN,50,2023-12-15T11:15:30+00:00,True,False

In [45]:
# Use .crosstab() function to return counts of specified variables
pd.crosstab(airportDF.type, airportDF.municipality)

municipality,Abrego,Acacias,Acandí,Acaricuara,Aguachica,Aguaclara,Aguazul,Aipe,Alvarado,Amalfi,...,Villavicencio,Villavieja,Vista Hermosa,Yaguara,Yari,Yavarate,Yopal,Zambrano,Zapatoca,Zarzal
type,,,,,,,,,,,,,,,,,,,,,
closed,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
heliport,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
large_airport,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
medium_airport,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
small_airport,1,2,3,1,4,0,5,1,4,1,...,12,2,1,1,1,1,5,2,1,2

In [46]:
pd.crosstab(airportDF.type, airportDF.type)

type            closed  heliport  large_airport  medium_airport  small_airport
type
closed              14         0              0               0              0
heliport             0        55              0               0              0
large_airport        0         0              1               0              0
medium_airport       0         0              0              59              0
small_airport        0         0              0               0            602

# **Questions for airport DataFrame**
1. How many airports above/below 5280' elevation?

2. How many medium sized airports?

3. How many heliports are in Bogota municipality?

In [50]:
high_aero = airportDF[airportDF['elevation_ft'] > 5280]

In [19]:
# How many airports above 5280' (1 mile = elevation of Denver, Colorado)?
airportDF['elev > 5280'] = airportDF.elevation_ft > 5280
airportDF.groupby('elev > 5280').describe()

                id                                                          \
             count          mean            std     min       25%      50%
elev > 5280
False        698.0  55116.030086   79150.534840  1644.0  40626.25  40803.5
True          33.0  61281.212121  113924.427419  6104.0   6158.00  40797.0

                                latitude_deg            ... scheduled_service  \
                  75%       max        count      mean  ...               75%
elev > 5280                                             ...
False        40986.75  519298.0        698.0  5.296178  ...               0.0
True         40966.00  517147.0         33.0  4.978349  ...               0.0

                  score                                                   \
             max  count         mean          std  min   25%   50%   75%
elev > 5280
False        1.0  698.0    88.467049   158.333365  0.0  50.0  50.0  50.0
True         1.0   33.0  1711.363636  8901.213688  0.0  50.0  50.0  50.0


                 max
elev > 5280
False          750.0
True         51275.0

[2 rows x 48 columns]

In [53]:
print('The number of airports locate above 5,280 ft is', airportDF
      [airportDF['elev > 5280']==True]['elev > 5280'].sum())

print('There are', len(high_aero), 'airports above 5280ft')

The number of airports locate above 5,280 ft is 33
There are 33 airports above 5280ft

In [31]:
# How many medium-sized airports?
airportDF['type_mid'] = airportDF['type'] == 'medium_airport'
airportDF[airportDF['type_mid']== True]['type_mid'].sum()

59

In [54]:
med_aero = airportDF[airportDF['type'] == 'medium_airport']

print('There are ', len(med_aero), 'mid sized airports')

There are  59 mid sized airports

In [33]:
# How many heliports?
airportDF[airportDF['type']== 'heliport']['type'].count()

55

In [67]:
bog_heli = airportDF[(airportDF['municipality'] == 'Bogota') & (airportDF['type'] == 'heliport')]

bog_heli

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,country_name,iso_country,...,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords,score,last_updated,elev > 5280,type_mid
679,45133,CO-0032,heliport,Hospital De Engativa Heliport,4.710556,-74.110000,NaN,SA,Colombia,CO,...,NaN,NaN,HOS,NaN,NaN,NaN,0,2012-06-08T20:09:32+00:00,False,False
681,45135,CO-0034,heliport,Fiscalia General De La Nacion Heliport,4.641944,-74.103333,NaN,SA,Colombia,CO,...,NaN,NaN,FIS,NaN,NaN,NaN,0,2012-06-08T19:48:21+00:00,False,False
686,45140,CO-0039,heliport,Proma Heliport,4.728056,-74.084444,NaN,NaN,Colombia,CO,...,NaN,NaN,NaN,NaN,NaN,NaN,0,2022-10-27T12:31:06+00:00,False,False
687,45142,CO-0041,heliport,Parque Central Bavaria Heliport,4.620278,-74.073333,NaN,SA,Colombia,CO,...,NaN,NaN,IPA,NaN,NaN,NaN,0,2012-06-08T19:33:10+00:00,False,False
690,45145,CO-0044,heliport,I.N.G. Barings Heliport,4.660556,-74.054444,NaN,SA,Colombia,CO,...,NaN,NaN,ING,NaN,NaN,NaN,0,2012-06-09T23:18:42+00:00,False,False
693,45148,CO-0047,heliport,Helitaxi Heliport,4.625833,-73.875556,NaN,SA,Colombia,CO,...,NaN,NaN,NaN,NaN,NaN,NaN,0,2010-08-29T23:22:06+00:00,False,False

## **Fiscalized Oil & Gas Production 2020**

This is another good example for doing pivots in pandas.

**Objective:** Want to make a plot that has the monthly values ($, gal) plotted as a function of month as a line graph with each line colored by _operadora_. Allow to compare the different companies month-to-month. Also, **GeoPark** is in this data set. Can you find it? ;)

In [71]:
# Define link to data url and open using pd.read_csv()
oil_prod_2020_url = ("https://www.datos.gov.co/resource/6v67-9pip.csv")
op20_df = pd.read_csv(oil_prod_2020_url)
op20_df

,departamento,municipio,latitud,longitud,geolocalizacion,operadora,contrato,campo,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,ANTIOQUIA,PUERTO NARE,6.126539,-74.703177,POINT (-74.70317722 6.126539139),ECOPETROL S.A.,TECA COCORNA,AREA TECA-COCORNA,1765.84,1689.32,1826.93,1537.57,1238.72,1049.21,975.58,949.00,943.07,1276.13,1327.46,1256.37
1,ANTIOQUIA,PUERTO NARE,6.126539,-74.703177,POINT (-74.70317722 6.126539139),MANSAROVAR ENERGY COLOMBIA LTD,NARE,NARE SUR,187.33,184.97,173.58,191.32,193.94,166.74,168.84,152.02,147.40,155.10,140.81,122.48
2,ANTIOQUIA,PUERTO NARE,6.126539,-74.703177,POINT (-74.70317722 6.126539139),MANSAROVAR ENERGY COLOMBIA LTD,NARE,UNDERRIVER,645.83,625.85,632.27,662.28,569.90,443.57,545.70,523.70,448.83,522.13,502.12,466.15
3,ANTIOQUIA,PUERTO TRIUNFO,5.954830,-74.686192,POINT (-74.6861918 5.954830151),ECOPETROL S.A.,TECA COCORNA,AREA TECA-COCORNA,119.70,118.32,81.96,0.00,0.00,0.00,14.05,104.08,94.44,76.66,76.14,74.72
4,ANTIOQUIA,YONDO,6.925159,-74.158240,POINT (-74.15824041 6.925159318),ECOPETROL S.A.,MAGDALENA MEDIO-CASABE,CASABE,11636.58,11584.22,11488.16,10711.52,9483.40,9402.73,9599.38,9527.73,9991.97,10483.05,10633.20,10530.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,CHENCHE,CHENCHE,50.84,50.48,49.64,49.05,48.73,48.54,46.38,47.71,47.38,46.85,46.54,45.89
441,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,ESPINAL,MATACHÍN NORTE,1215.96,1239.39,1261.90,1317.66,1339.26,1285.89,1298.55,1238.69,1218.94,1257.85,1191.10,1234.90
442,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,ESPINAL,MATACHÍN SUR,80.30,105.55,120.17,124.08,118.16,115.42,116.88,114.25,114.73,108.33,104.18,103.09
443,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,ESPINAL,PURIFICACIÓN,52.02,50.97,51.14,51.94,21.91,0.00,0.00,0.00,0.00,0.00,0.00,0.00
444,TOLIMA,SAN LUIS,4.057272,-75.163208,POINT (-75.16320806 4.057271684),HOCOL S.A.,ORTEGA,PACANDE,52.59,64.71,42.88,62.84,59.10,21.03,0.00,0.00,0.00,65.92,67.56,71.86

In [72]:
op20_df.index = op20_df.index.rename('oil_gas_id')
op20_df

,departamento,municipio,latitud,longitud,geolocalizacion,operadora,contrato,campo,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
oil_gas_id,,,,,,,,,,,,,,,,,,,,
0,ANTIOQUIA,PUERTO NARE,6.126539,-74.703177,POINT (-74.70317722 6.126539139),ECOPETROL S.A.,TECA COCORNA,AREA TECA-COCORNA,1765.84,1689.32,1826.93,1537.57,1238.72,1049.21,975.58,949.00,943.07,1276.13,1327.46,1256.37
1,ANTIOQUIA,PUERTO NARE,6.126539,-74.703177,POINT (-74.70317722 6.126539139),MANSAROVAR ENERGY COLOMBIA LTD,NARE,NARE SUR,187.33,184.97,173.58,191.32,193.94,166.74,168.84,152.02,147.40,155.10,140.81,122.48
2,ANTIOQUIA,PUERTO NARE,6.126539,-74.703177,POINT (-74.70317722 6.126539139),MANSAROVAR ENERGY COLOMBIA LTD,NARE,UNDERRIVER,645.83,625.85,632.27,662.28,569.90,443.57,545.70,523.70,448.83,522.13,502.12,466.15
3,ANTIOQUIA,PUERTO TRIUNFO,5.954830,-74.686192,POINT (-74.6861918 5.954830151),ECOPETROL S.A.,TECA COCORNA,AREA TECA-COCORNA,119.70,118.32,81.96,0.00,0.00,0.00,14.05,104.08,94.44,76.66,76.14,74.72
4,ANTIOQUIA,YONDO,6.925159,-74.158240,POINT (-74.15824041 6.925159318),ECOPETROL S.A.,MAGDALENA MEDIO-CASABE,CASABE,11636.58,11584.22,11488.16,10711.52,9483.40,9402.73,9599.38,9527.73,9991.97,10483.05,10633.20,10530.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,CHENCHE,CHENCHE,50.84,50.48,49.64,49.05,48.73,48.54,46.38,47.71,47.38,46.85,46.54,45.89
441,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,ESPINAL,MATACHÍN NORTE,1215.96,1239.39,1261.90,1317.66,1339.26,1285.89,1298.55,1238.69,1218.94,1257.85,1191.10,1234.90
442,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,ESPINAL,MATACHÍN SUR,80.30,105.55,120.17,124.08,118.16,115.42,116.88,114.25,114.73,108.33,104.18,103.09
443,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,ESPINAL,PURIFICACIÓN,52.02,50.97,51.14,51.94,21.91,0.00,0.00,0.00,0.00,0.00,0.00,0.00
444,TOLIMA,SAN LUIS,4.057272,-75.163208,POINT (-75.16320806 4.057271684),HOCOL S.A.,ORTEGA,PACANDE,52.59,64.71,42.88,62.84,59.10,21.03,0.00,0.00,0.00,65.92,67.56,71.86

In [57]:
# Renaming the index column using .index.rename()
op20_df.index.rename('oil_gas_id', inplace= True)

# Selecting data up through a specified column 'campo' using .loc
op20_df.set_index('campo')

,departamento,municipio,latitud,longitud,geolocalizacion,operadora,contrato,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
campo,,,,,,,,,,,,,,,,,,,
AREA TECA-COCORNA,ANTIOQUIA,PUERTO NARE,6.126539,-74.703177,POINT (-74.70317722 6.126539139),ECOPETROL S.A.,TECA COCORNA,1765.84,1689.32,1826.93,1537.57,1238.72,1049.21,975.58,949.00,943.07,1276.13,1327.46,1256.37
NARE SUR,ANTIOQUIA,PUERTO NARE,6.126539,-74.703177,POINT (-74.70317722 6.126539139),MANSAROVAR ENERGY COLOMBIA LTD,NARE,187.33,184.97,173.58,191.32,193.94,166.74,168.84,152.02,147.40,155.10,140.81,122.48
UNDERRIVER,ANTIOQUIA,PUERTO NARE,6.126539,-74.703177,POINT (-74.70317722 6.126539139),MANSAROVAR ENERGY COLOMBIA LTD,NARE,645.83,625.85,632.27,662.28,569.90,443.57,545.70,523.70,448.83,522.13,502.12,466.15
AREA TECA-COCORNA,ANTIOQUIA,PUERTO TRIUNFO,5.954830,-74.686192,POINT (-74.6861918 5.954830151),ECOPETROL S.A.,TECA COCORNA,119.70,118.32,81.96,0.00,0.00,0.00,14.05,104.08,94.44,76.66,76.14,74.72
CASABE,ANTIOQUIA,YONDO,6.925159,-74.158240,POINT (-74.15824041 6.925159318),ECOPETROL S.A.,MAGDALENA MEDIO-CASABE,11636.58,11584.22,11488.16,10711.52,9483.40,9402.73,9599.38,9527.73,9991.97,10483.05,10633.20,10530.89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CHENCHE,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,CHENCHE,50.84,50.48,49.64,49.05,48.73,48.54,46.38,47.71,47.38,46.85,46.54,45.89
MATACHÍN NORTE,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,ESPINAL,1215.96,1239.39,1261.90,1317.66,1339.26,1285.89,1298.55,1238.69,1218.94,1257.85,1191.10,1234.90
MATACHÍN SUR,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,ESPINAL,80.30,105.55,120.17,124.08,118.16,115.42,116.88,114.25,114.73,108.33,104.18,103.09
PURIFICACIÓN,TOLIMA,PURIFICACIÓN,3.854282,-74.874512,POINT (-74.87451155 3.854281614),HOCOL S.A.,ESPINAL,52.02,50.97,51.14,51.94,21.91,0.00,0.00,0.00,0.00,0.00,0.00,0.00
PACANDE,TOLIMA,SAN LUIS,4.057272,-75.163208,POINT (-75.16320806 4.057271684),HOCOL S.A.,ORTEGA,52.59,64.71,42.88,62.84,59.10,21.03,0.00,0.00,0.00,65.92,67.56,71.86

In [58]:
# Melting the data to examine values by specifed month
op20_month_df = (
    op20_df
    .loc[:,'enero':'diciembre']
    .reset_index()
    .melt(id_vars='oil_gas_id', var_name='month_name', value_name='value'))
op20_month_df

      oil_gas_id month_name     value
0              0      enero   1765.84
1              1      enero    187.33
2              2      enero    645.83
3              3      enero    119.70
4              4      enero  11636.58
...          ...        ...       ...
5335         440  diciembre     45.89
5336         441  diciembre   1234.90
5337         442  diciembre    103.09
5338         443  diciembre      0.00
5339         444  diciembre     71.86

[5340 rows x 3 columns]

In [68]:
# Explore data using .info() method
op20_month_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5340 entries, 0 to 5339
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   oil_gas_id  5340 non-null   int64
 1   month_name  5340 non-null   object
 2   value       5340 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 125.3+ KB

In [69]:
# How many entries for each variable 'departmento'? Hint: df.groupby('col_name').size()
op20_df.groupby('departamento').size()

departamento
ANTIOQUIA               7
ARAUCA                 24
ATLANTICO               2
BOLIVAR                 4
BOYACA                 12
CASANARE              169
CAUCA                   3
CESAR                  14
CORDOBA                 3
CUNDINAMARCA            2
HUILA                  28
MAGDALENA               6
META                   77
NARIÑO                  1
NORTE DE SANTANDER      4
PUTUMAYO               27
SANTANDER              35
SUCRE                   3
TOLIMA                 24
dtype: int64

In [70]:
# How many entries for each variable 'operadora' ?
op20_df.groupby('operadora').size()

operadora
AMERISUR EXPLORACION COLOMBIA LTD                                       1
CANACOL ENERGY COLOMBIA SAS                                             3
CARRAO ENERGY S.A. SUCURSAL COLOMBIA                                    6
CEPSA COLOMBIA S.A.                                                    19
COLOMBIA ENERGY DEVELOPMENT CO                                          8
COMPAÑIA OPERADORA PETROCOLOMBIA S.A.S - COPP                           3
ECOPETROL S.A.                                                        105
EMERALD ENERGY PLC SUCURSAL COLOMBIA                                   10
EQUION ENERGÍA LIMITED                                                  4
Frontera Energy Colombia Corp Sucursal Colombia                        66
GEOPARK COLOMBIA S.A.S.                                                11
GEOPRODUCTION OIL AND GAS COMPANY OF COLOMBIA                           1
GRAN TIERRA ENERGY COLOMBIA LTD                                        22
HADES E&P COLOMBIA S.A.S                                                2
HOCOL S.A.                                                             32
HUPECOL OPERATING CO LLC                                                1
INTEROIL COLOMBIA EXPLORATION AND PRODUCTION                            4
INVEPETROL LIMITED COLOMBIA                                             3
Iberoamericana de Hidrocarburos CQ Exploración y Producción S.A.S.      3
LAS QUINCHAS RESOURCE CORP SURCURSAL COLOMBIA                           4
LEWIS ENERGY COLOMBIA INC                                               6
MANSAROVAR ENERGY COLOMBIA LTD                                          8
NEW GRANADA ENERGY CORPORATION SUCURSAL COLOMBIA                        7
NIKOIL ENERGY CORP                                                      1
OIRU CORPORATION                                                        3
OMNIA.ENERGY INC. SUCURSAL COLOMBIA                                     1
ONGC VIDESH LIMITED SUCURSAL COLOMBIANA                                 2
PAREX RESOURCES COLOMBIA LTD. SUCURSAL                                 14
PERENCO COLOMBIA LIMITED                                               35
PERENCO OIL AND GAS COLOMBIA LIMITED.                                   9
PETROLEOS COLOMBIANOS SA                                                1
PETROLEOS SUD AMERICANOS SUCURSAL COLOMBIA                              3
PETROSANTANDER (COLOMBIA) INC.                                          6
SIERRACOL ENERGY ARAUCA LLC                                            22
SUELOPETROL, C.A. SUCURSAL COLOMBIA                                     1
TABASCO OIL COMPANY LLC                                                 1
TECPETROL COLOMBIA SAS                                                  4
TPL COLOMBIA LTD - SUCURSAL COLOMBIA                                    1
UNION TEMPORAL OMEGA ENERGY                                             2
VERANO ENERGY (BARBADOS) LIMITED                                        4
VETRA EXPLORACION Y PRODUCCION COLOMBIA S.A.S.                          5
WATTLE PETROLEUM COMPANY S.A.S                                          1
dtype: int64

## **Look exclusively at GeoPark**

In [73]:
# Select out all Geopark entries
gpk = op20_df[op20_df['operadora'].isin(['GEOPARK COLOMBIA S.A.S.'])]
gpk

,departamento,municipio,latitud,longitud,geolocalizacion,operadora,contrato,campo,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
oil_gas_id,,,,,,,,,,,,,,,,,,,,
166,CASANARE,TAURAMENA,4.697464,-72.629224,POINT (-72.62922436 4.697463691),GEOPARK COLOMBIA S.A.S.,LLA 34,CHACHALACA,113.34,106.82,47.23,0.00,0.00,0.00,0.00,0.00,5.63,0.00,0.00,0.00
167,CASANARE,TAURAMENA,4.697464,-72.629224,POINT (-72.62922436 4.697463691),GEOPARK COLOMBIA S.A.S.,LLA 34,CHIRICOCA,3161.00,2083.84,998.10,736.34,594.99,510.48,444.18,232.58,552.95,709.39,647.14,595.74
174,CASANARE,TAURAMENA,4.697464,-72.629224,POINT (-72.62922436 4.697463691),GEOPARK COLOMBIA S.A.S.,LLA 34,MAX,261.23,261.23,170.01,0.00,0.00,0.00,0.00,0.00,91.79,258.76,261.09,260.55
176,CASANARE,TAURAMENA,4.697464,-72.629224,POINT (-72.62922436 4.697463691),GEOPARK COLOMBIA S.A.S.,LLA 34,TARO TARO,399.42,396.04,267.40,0.00,0.00,0.00,124.25,288.22,279.74,178.17,0.00,0.00
177,CASANARE,TAURAMENA,4.697464,-72.629224,POINT (-72.62922436 4.697463691),GEOPARK COLOMBIA S.A.S.,LLA 34,TIGANA,34987.24,36756.21,35999.17,33587.72,28047.20,32174.75,31397.15,31559.50,30117.54,28019.94,27583.03,29235.58
178,CASANARE,TAURAMENA,4.697464,-72.629224,POINT (-72.62922436 4.697463691),GEOPARK COLOMBIA S.A.S.,LLA 34,TILO,355.12,381.57,234.14,0.00,0.00,0.00,7.88,333.38,341.01,340.82,337.31,337.97
180,CASANARE,TAURAMENA,4.697464,-72.629224,POINT (-72.62922436 4.697463691),GEOPARK COLOMBIA S.A.S.,LLA 34,TUA,4318.55,4205.95,3819.69,3868.82,268.86,1879.47,3110.47,3216.57,3040.73,3005.79,3015.73,3143.31
198,CASANARE,VILLA NUEVA,4.528308,-72.823143,POINT (-72.82314281 4.528307719),GEOPARK COLOMBIA S.A.S.,LLA 34,CURUCUCÚ,225.94,218.95,135.63,0.00,0.00,0.00,0.00,0.00,64.18,197.57,196.46,182.15
199,CASANARE,VILLA NUEVA,4.528308,-72.823143,POINT (-72.82314281 4.528307719),GEOPARK COLOMBIA S.A.S.,LLA 34,GUACO,381.67,350.26,194.79,0.00,0.00,0.00,302.84,326.98,272.37,244.87,219.60,183.29
200,CASANARE,VILLA NUEVA,4.528308,-72.823143,POINT (-72.82314281 4.528307719),GEOPARK COLOMBIA S.A.S.,LLA 34,JACAMAR,33.85,30.83,18.90,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
201,CASANARE,VILLA NUEVA,4.528308,-72.823143,POINT (-72.82314281 4.528307719),GEOPARK COLOMBIA S.A.S.,LLA 34,JACANA,26365.64,27510.23,29643.37,26851.45,23547.94,22050.82,23870.71,24764.39,25432.18,24556.76,24133.06,23855.03

In [ ]:
# Select 'campo' and each of the 12 month columns and make new df


# Group by 'campo' and sum for each month

In [ ]:
# Select out single month from gpk_campo_group and calculate sum

In [ ]:
# Transpose DataFrame

In [ ]:
# Plot each variable (campo) as function of month on same axis

In [ ]:
# Drop the outlier JACAMAR & TIGANA using .drop()

In [ ]:
# Plot each variable (campo) as function of month on same axis

## **Look at all operadoras**

In [ ]:
# Select 'operadora' and each of the 12 month columns and make new df

In [ ]:
# Group by 'operadora' then sum -> return single entry per company per month

In [ ]:
# Transpose the DataFrame

In [ ]:
# Give index_col name of 'months'

In [ ]:
# Return list of column names for transposed DataFrame

In [ ]:
# Plot columns (operadora) one-at-a-time

In [ ]:
# Drop the outlier ECOPETROL S.A.

In [ ]:
# Plot each variable (company name) as function of month on same axis

# Look at all Departamentos

In [ ]:
# Group by 'departamento' then sum -> return single entry per dept. per month

# Select only columns with numeric values

# Drop lat/long columns

In [ ]:
# Transpose data

# Give index_col name of 'months'

In [ ]:
# Plot each variable (Departamento) as function of month on same axis

# **Questions for production DataFrame**
**1.** What was the total production for GPK in agosto 2020?

**2.** How many field sites (campo) are in the XXX Departamento?

**3.** Create a plot comparing GPK to other two operators (operadora) of your choice.

In [ ]:
# Looking at global oil production using another data set from OECD

global_oil_url = "https://stats.oecd.org/sdmx-json/data/DP_LIVE/.OILPROD.TOT.KTOE.A/OECD?contentType=csv&detail=code&separator=comma&csv-lang=en&startPeriod=1960&endPeriod=2021"

global_oil_df = pd.read_csv(global_oil_url)
print(global_oil_df)

# Select COLOMBIA and print first 5 rows


# Plot Colombia data